'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5472
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5472.
'
Namespace CMMON
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CMMon2ServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CMMon2Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://10.11.40.15:1083/CMMon2Service.asmx"
        End Sub

        Public Sub New(ByVal s As String)
            MyBase.New()
            Me.Url = s
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegisterInfo(ByVal TerminalID As String, ByVal Brigada As String, ByVal Tnum As String) As Boolean
            Dim results() As Object = Me.Invoke("RegisterInfo", New Object() {TerminalID, Brigada, Tnum})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginRegisterInfo(ByVal TerminalID As String, ByVal Brigada As String, ByVal Tnum As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RegisterInfo", New Object() {TerminalID, Brigada, Tnum}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRegisterInfo(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterPodInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegisterPodInfo(ByVal TerminalID As String, ByVal POD As String, ByVal WP As String, ByVal QWORKERS As Integer, ByVal STATUSID As Integer, ByVal opPRC As Integer, ByVal BRK As Integer, ByVal WPChanged As Boolean, ByVal QWORKERSChanged As Boolean, ByVal STATUSChanged As Boolean, ByVal opPRCChanged As Boolean, ByVal BRKChanged As Boolean) As Boolean
            Dim results() As Object = Me.Invoke("RegisterPodInfo", New Object() {TerminalID, POD, WP, QWORKERS, STATUSID, opPRC, BRK, WPChanged, QWORKERSChanged, STATUSChanged, opPRCChanged, BRKChanged})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginRegisterPodInfo(ByVal TerminalID As String, ByVal POD As String, ByVal WP As String, ByVal QWORKERS As Integer, ByVal STATUSID As Integer, ByVal opPRC As Integer, ByVal BRK As Integer, ByVal WPChanged As Boolean, ByVal QWORKERSChanged As Boolean, ByVal STATUSChanged As Boolean, ByVal opPRCChanged As Boolean, ByVal BRKChanged As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RegisterPodInfo", New Object() {TerminalID, POD, WP, QWORKERS, STATUSID, opPRC, BRK, WPChanged, QWORKERSChanged, STATUSChanged, opPRCChanged, BRKChanged}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRegisterPodInfo(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NewPod", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function NewPod(ByVal TerminalID As String, ByVal POD As String) As Boolean
            Dim results() As Object = Me.Invoke("NewPod", New Object() {TerminalID, POD})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginNewPod(ByVal TerminalID As String, ByVal POD As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("NewPod", New Object() {TerminalID, POD}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndNewPod(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerifyPod", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function VerifyPod(ByVal TerminalID As String, ByVal POD As String) As String
            Dim results() As Object = Me.Invoke("VerifyPod", New Object() {TerminalID, POD})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginVerifyPod(ByVal TerminalID As String, ByVal POD As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("VerifyPod", New Object() {TerminalID, POD}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndVerifyPod(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ping", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Ping(ByVal TerminalID As Integer, ByVal Address As String)
            Me.Invoke("Ping", New Object() {TerminalID, Address})
        End Sub
        
        '''<remarks/>
        Public Function BeginPing(ByVal TerminalID As Integer, ByVal Address As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Ping", New Object() {TerminalID, Address}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndPing(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMaxStatus", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMaxStatus() As Integer
            Dim results() As Object = Me.Invoke("GetMaxStatus", New Object(-1) {})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginGetMaxStatus(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetMaxStatus", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetMaxStatus(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStatusName", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStatusName(ByVal id As Integer) As String
            Dim results() As Object = Me.Invoke("GetStatusName", New Object() {id})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetStatusName(ByVal id As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetStatusName", New Object() {id}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetStatusName(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddStatus", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddStatus(ByVal id As Integer, ByVal name As String) As Boolean
            Dim results() As Object = Me.Invoke("AddStatus", New Object() {id, name})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginAddStatus(ByVal id As Integer, ByVal name As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddStatus", New Object() {id, name}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndAddStatus(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOPInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetOPInfo(ByVal OpCode As String) As String
            Dim results() As Object = Me.Invoke("GetOPInfo", New Object() {OpCode})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetOPInfo(ByVal OpCode As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetOPInfo", New Object() {OpCode}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetOPInfo(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTerminalOperations", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTerminalOperations(ByVal terminalid As String) As String
            Dim results() As Object = Me.Invoke("GetTerminalOperations", New Object() {terminalid})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetTerminalOperations(ByVal terminalid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTerminalOperations", New Object() {terminalid}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetTerminalOperations(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
