CREATE TABLE "OPC"."CMMON2_PODINFO" 
   (	"TERMINALID" NUMBER(18,0) NOT NULL ENABLE, 
	"PODEVENTDATE" DATE NOT NULL ENABLE, 
	"POD" VARCHAR2(20) NOT NULL ENABLE, 
	"WP" VARCHAR2(20), 
	"QWORKERS" NUMBER(18,0), 
	"STATUSID" NUMBER(18,0), 
	"OPPRC" NUMBER(18,0), 
	"BRK" NUMBER(18,0), 
	"SAVED2SAP" NUMBER(1,0), 
	"LMNGA" NUMBER(10,0) DEFAULT 0, 
	"BRIG" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USR" ;
  ALTER TABLE "OPC"."CMMON2_PODINFO" MODIFY ("POD" NOT NULL ENABLE);
  ALTER TABLE "OPC"."CMMON2_PODINFO" MODIFY ("PODEVENTDATE" NOT NULL ENABLE);
  ALTER TABLE "OPC"."CMMON2_PODINFO" MODIFY ("TERMINALID" NOT NULL ENABLE);


CREATE TABLE "OPC"."CMMON2_PODVRF" 
   (	"TERMINALID" NUMBER(18,0) NOT NULL ENABLE, 
	"POD" VARCHAR2(20) NOT NULL ENABLE, 
	"PODEVENTDATE" DATE NOT NULL ENABLE, 
	"PROCESSSTATUS" NUMBER(18,0), 
	"PROCESSMSG" VARCHAR2(128), 
	"OCHER" NUMBER(1,0) DEFAULT 0, 
	"BRIG" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USR" ;
  ALTER TABLE "OPC"."CMMON2_PODVRF" MODIFY ("PODEVENTDATE" NOT NULL ENABLE);
  ALTER TABLE "OPC"."CMMON2_PODVRF" MODIFY ("POD" NOT NULL ENABLE);
  ALTER TABLE "OPC"."CMMON2_PODVRF" MODIFY ("TERMINALID" NOT NULL ENABLE);


CREATE TABLE "OPC"."CMMON2_INFO" 
   (	"TERMINALID" NUMBER(18,0) NOT NULL ENABLE, 
	"TN" VARCHAR2(20), 
	"EVENTDATE" DATE NOT NULL ENABLE, 
	"TNUM" VARCHAR2(40), 
	"LASTPING" DATE, 
	"IPADDR" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USR" ;
  ALTER TABLE "OPC"."CMMON2_INFO" MODIFY ("EVENTDATE" NOT NULL ENABLE);
  ALTER TABLE "OPC"."CMMON2_INFO" MODIFY ("TERMINALID" NOT NULL ENABLE);